# SafetySnap Django Auto-Restart Script
# Generated by Ansible at 2025-11-02T16:46:33Z

Write-Host "🔄 Restarting Django Server..." -ForegroundColor Yellow
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Yellow

cd "D:\PROJECTS\SafetySnap\backend"

Write-Host "✅ Dependencies: INSTALLED" -ForegroundColor Green
Write-Host "✅ Migrations: APPLIED" -ForegroundColor Green
Write-Host "✅ Static Files: COLLECTED" -ForegroundColor Green
Write-Host ""
Write-Host "Starting Django Server..." -ForegroundColor Cyan
Write-Host ""

python manage.py runserver 0.0.0.0:8000

Write-Host ""
Write-Host "🎉 Django Started Successfully!" -ForegroundColor Green
Write-Host "📊 Health Check: http://172.18.32.1:8000/api/health/" -ForegroundColor Cyan
