# Generated by Django 5.1 on 2025-10-04 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_scans', models.IntegerField(default=0)),
                ('total_persons', models.IntegerField(default=0)),
                ('compliant_persons', models.IntegerField(default=0)),
                ('non_compliant_persons', models.IntegerField(default=0)),
                ('helmet_violations', models.IntegerField(default=0)),
                ('vest_violations', models.IntegerField(default=0)),
                ('boots_violations', models.IntegerField(default=0)),
                ('gloves_violations', models.IntegerField(default=0)),
                ('glasses_violations', models.IntegerField(default=0)),
                ('compliance_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='users.site')),
            ],
            options={
                'db_table': 'compliance_metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['site', '-date'], name='compliance__site_id_2e6532_idx')],
                'unique_together': {('site', 'date')},
            },
        ),
    ]
