# Generated by Django 5.1 on 2025-10-05 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persondetection',
            unique_together={('detection', 'person_id')},
        ),
        migrations.AlterField(
            model_name='persondetection',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='persondetection',
            name='detection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_detections', to='ppe_detection.detection'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='person_detection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='ppe_detection.persondetection'),
        ),
        migrations.AlterModelTable(
            name='persondetection',
            table=None,
        ),
        migrations.RemoveField(
            model_name='persondetection',
            name='created_at',
        ),
    ]
