# Generated by Django 5.1 on 2025-10-06 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe_detection', '0002_alter_persondetection_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger'), ('info', 'Info')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppe_detection.detection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('violation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppe_detection.violation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
