# Generated by Django 5.1 on 2025-10-28 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe_detection', '0003_notification'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='model_used',
            field=models.CharField(choices=[('best', 'Best (Custom Trained)'), ('yolov8n', 'YOLOv8 Nano'), ('yolo11n', 'YOLO11 Nano')], default='best', help_text='YOLO model used for detection', max_length=20),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['model_used'], name='detections_model_u_6925f1_idx'),
        ),
    ]
