# Generated by Django 5.1 on 2025-10-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe_detection', '0004_detection_model_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='model_used',
            field=models.CharField(choices=[('best', 'Best'), ('yolov8n', 'YOLOv8n'), ('yolo11n', 'YOLO11n')], default='best', max_length=20),
        ),
    ]
