# Generated by Django 5.1 on 2025-10-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe_detection', '0005_alter_detection_model_used'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='detection',
            name='detections_model_u_6925f1_idx',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='model_used',
        ),
    ]
