# Generated by Django 5.1 on 2025-10-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe_detection', '0006_remove_detection_detections_model_u_6925f1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='model_used',
            field=models.CharField(blank=True, default='YOLO11n', max_length=100),
        ),
    ]
